### ISSUE TITLE
Frontend: Remove Recipe from User's Favorite List

### ISSUE THREAD

**Issue by linhpham99** [giangvubinhng/foodrecipe-client#10]

**Comment by zincusita** [comment]
COMPLETED:
wrote backend to get user_favorites
visually list user_favorites from backend
display user first and last name for profile

TODO FAVORITES:
set onClick under 'Favorites' to link to that recipe page
create `add to favorites` button for any recipe page

TODO AUTHORED:
visually list user's written recipes
implement delete button
if they click on it, it hyperlinks to the recipe page where they can edit the recipe

* commented out <React.StrictMode> in main.jsx because I got annoyed with the repeated printing to console
* Add Recipe button currently broken - not sure why; have not pulled latest main with Linh's fix-method yet though so still need to do that

**Comment by zincusita** [comment]
Completed in add recipe to user favorite
